# Generated by Django 2.0.6 on 2018-06-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180628_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu',
            new_name='titulo_menu',
        ),
    ]
